export interface NetworkConfig {
  PROVIDER_ID: number
  NETWORK_ID: number
  CHAIN_NETWORK_ID: string
  IS_MAINNET: boolean
  EXPLORER_URL_FOR_ADDRESS: (address: string) => any
  EXPLORER_URL_FOR_TX: (tx: string) => any
  BASE_CONFIG: [
    {
      // shelley-era
      START_AT: number
      SLOTS_PER_EPOCH: number
      SLOT_DURATION: number
    }
  ]
}

export const CONFIG_NUMBERS = {
  HARD_DERIVATION_START: 2147483648,
  WALLET_TYPE_PURPOSE: {
    BIP44: 2147483692, // HARD_DERIVATION_START + 44;
    CIP1852: 2147485500, // HARD_DERIVATION_START + 1852;
  },
  COIN_TYPES: {
    CARDANO: 2147485463, // HARD_DERIVATION_START + 1815;
  },
  ACCOUNT_INDEX: 0,
  STAKING_ACCOUNT_INDEX: 0,
}

export const NETWORK_REGISTRY = {
  BYRON_MAINNET: 0,
  HASKELL_SHELLEY: 1,
  JORMUNGANDR: 100,
  // ERGO: 200,
  HASKELL_SHELLEY_TESTNET: 300,
  UNDEFINED: -1,
}

export const ROLE_TYPE = {
  EXTERNAL_CHAIN: 0,
  INTERNAL_CHAIN: 1,
  STAKING_KEY: 2,
}
