
auth.token=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

defaults.org=bonfire-jg
defaults.project=react-native

defaults.url=https://sentry.io/
