require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'bonfire' do
  config = use_native_modules!
  
 def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
 end

 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-haskell-shelley', :path => '../node_modules/@emurgo/csl-mobile-bridge'

  target 'bonfireTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  # ⬇️ uncomment wanted permissions
   setup_permissions([
     # 'AppTrackingTransparency',
     # 'Bluetooth',
     # 'Calendars',
     # 'CalendarsWriteOnly',
      'Camera',
     # 'Contacts',
      'FaceID',
     # 'LocationAccuracy',
     # 'LocationAlways',
      'LocationWhenInUse',
      'MediaLibrary',
     # 'Microphone',
     # 'Motion',
     # 'Notifications',
      'PhotoLibrary',
     # 'PhotoLibraryAddOnly',
     # 'Reminders',
     # 'Siri',
     # 'SpeechRecognition',
     # 'StoreKit',
   ])
end
